<?php
      $events = array(
      #User common eventts
	"1"=>"User logon",
	"2"=>"User logout",
	"3"=>"A user was created",
	"5"=>"Personal password was changed",
	"6"=>"User personal data was changed",
	"7"=>"Password expired. User is blocked",
	"8"=>"Unsuccessful login attempt. User is bloked",
	"9"=>"Unsuccessful login attempt. User is deleted",
	"10"=>"Unsuccessful login attempt. Wrong login or password",
	"11"=>"User was automatically logged off while in operation due to having been deleted",
	"12"=>"User was automatically logged off while in operation due to having been blocked",
	"13"=>"Unsuccessful login attempt. Number of unsuccessful login attempts exceeded the limit. User was blocked",
	"14"=>"User was blocked for his/her personal data was changed by",
	"15"=>"User was deleted by",
	"16"=>"User was unblocked by / on",
	"17"=>"User was blocked by / on",
	"18"=>"User login attempts nuber was changed by / from / to / on",
	"19"=>"User password validity days was changed by / from / to / on",
      #Operator and supervisor specific events
	"20"=>"Changing a scenary",
	"21"=>"Initiating a reconciliation",
	"22"=>"Initiating a reconciliation",
	"23"=>"Putting off a reconciliation",
	"24"=>"Confirm a reconciliation",
	"25"=>"Handing over a reconciliation to a supervisor.",
      #Supervisor specific events
	"26"=>"Confirming a discrepancy",
	"27"=>"Changing the cashroom for a user",
	"28"=>"Resolving an index conflict",
	"29"=>"Merging deposits",
      #Administrator specific events
	"41"=>"Creating a new machine type",
	"42"=>"Creating a new machine",
	"43"=>"Creating a scenary",
	"44"=>"Creating a customer",
	"45"=>"Creating a cashroom",
	"46"=>"Creating a currency",
	"47"=>"Creating a denomination",
	"48"=>"Creating a grade",
	"49"=>"Creating a valuable",
	"50"=>"Editing system globals",
	"51"=>"Editing machine type",
	"52"=>"Editing a machine",
	"53"=>"Editing a customer",
	"54"=>"Editing a cashroom",
	"55"=>"Editing a currency",
	"56"=>"Editing a denomination",
	"57"=>"Editing a grade",
	"58"=>"Editing a valuable",
	"59"=>"Logically deleting a user",
	"60"=>"Logically deleting a customer",
	"61"=>"Logically deleting a machine",
	"62"=>"Logically deleting a scenary",
	"63"=>"On request database archive was created",
      #Security officer specific events
	"80"=>"Blocking a user",
	"81"=>"Unblocking a user",
	"82"=>"Changing password validity term",
	"83"=>"Changing password length for a role",
      #Machine specific events
	"100"=>"Machine connection resored",
	"101"=>"Machine connection lost",
	"102"=>"A corrupted file was received",
        "103"=>"ReportSet was generated",
        "104"=>"Regular database archive was created"

);
